addons:
  apt:
    sources:
      - mysql-8.0-trusty
    packages:
      - mysql-server
      - mysql-client
      - rabbitmq-server
services:
  - mysql
  - rabbitmq
  - elasticsearch

language: php
php:
  - 7.4
  - 8.1

env:
  matrix:
    - MAGENTO_VERSION=2.4

before_install:
  - composer self-update --1
  - git clone --depth=50 --branch=$MAGENTO_VERSION https://github.com/magento/magento2.git /tmp/magento
  - mysql -uroot -e 'SET @@global.sql_mode = NO_ENGINE_SUBSTITUTION; CREATE DATABASE magento_integration_tests;'
  - mv $(pwd)/install-config-mysql.travis.$MAGENTO_VERSION.php /tmp/magento/dev/tests/integration/etc/install-config-mysql.php
  - mkdir -p /tmp/magento/app/code/Firegento
  - cp -R $(pwd) /tmp/magento/app/code/Firegento/ContentProvisioning

install:
  - cd /tmp/magento
  - composer install --no-interaction
  - composer require --dev mikey179/vfsstream

script:
  - php /tmp/magento/vendor/bin/phpunit -c /tmp/magento/app/code/Firegento/ContentProvisioning/Test/Integration/phpunit.travis.xml
